### ISSUE TITLE
MacOS: when `rarfile` uses bsdtar as alternative, RAR comments aren't parsed

### ISSUE THREAD

**Issue by speidy** [markokr/rarfile#51]
Hello,

I'm running MacOS High-Sierra, and its seems like `rarfile` module will use `bsdtar` binary as `unrar` is not installed by default.

One problem with that is the archive comments aren't being decoded and it fools the user to think like there aren't any comment even though they actually appear in the .rar archive.

I think that a warning should be thrown to the user in this case. 

I personally don't like the `bsdtar` fallback as there are many feature lacks when using it (as commented in the comments of the module)

**Comment by markokr** [comment]
In addition issues mentioned in module comment, libarchive does not support some compression opcodes.

I think throwing warning just because extraction of a comment failed is wrong, its not big enough problem. Especially as extraction of actual files will probably fail soon.

I'll look into supporting unar, it should give better fallback than bsdtar.
