### ISSUE TITLE
BadRARFile "failed the read enough data"

### ISSUE THREAD

**Issue by ImBadImSorry** [markokr/rarfile#68]
Hello,

This is my first time using GitHub and reporting an issue so I apologize if I don't do things correctly. Now, to the issue.
I'm using the latest version of rarfile and I've recently been getting these read errors with when attempting to extract ZIP files. For some reason it **really** doesn't like my ZIP files. Anyway here is the log:

Failed the read enough data: req=1048576 got=0
  File "C:\Python39\Lib\site-packages\rarfile.py", line 2197, in read
    raise BadRarFile("Failed the read enough data: req=%d got=%d" % (orig, len(data)))
  File "C:\Python39\Lib\shutil.py", line 202, in copyfileobj
    buf = fsrc_read(length)
  File "C:\Python39\Lib\site-packages\rarfile.py", line 927, in _make_file
    shutil.copyfileobj(src, dst)
  File "C:\Python39\Lib\site-packages\rarfile.py", line 912, in _extract_one
    return self._make_file(info, dstfn, pwd, set_attrs)
  File "C:\Python39\Lib\site-packages\rarfile.py", line 826, in extract
    return self._extract_one(inf, path, pwd, True)
  File "D:\Python Test Folder\DAZV4.py", line 407, in HandleRAR
    rf.extract(x)
  File "D:\Python Test Folder\DAZV4.py", line 462, in <module>
    HandleRAR(DraggedFile)

I've attempted to extract using the extract method and using open method which I realized both use the same read method that is throwing an error. 

If you need the file that is tossing the error, just let me know.

**Comment by ImBadImSorry** [comment]
Also note that I've been using this since version 3.1 which worked great until I recently updated to Python 3.9.

**Comment by ahsieh1278** [comment]
I have a similar issue with same error but just when trying to uncompress RAR package instead of ZIP. 

It seems like, for the same RAR package which contains multiple files, some of the file extraction will be categorized as different compress_type for the failed case(e.g. most of the file in the package being marked as RAR_M0 while the failed file being marked as RAR_M3) which will result in the logic assign the different handlers to process the compressed file (RAR_M0 uses self._open_clear(inf) from CommonParser while RAR_M3 will use self._open_unrar(self._rarfile, inf, pwd) which will generate a totally different result as the PipeReader doesn't seem to be able to read the file correctly and will always result in empty data (I have the latest unrar.exe from official website). 

I don't know this RAR file format enough to further debugging the issue, but it seems weird that the same RAR package will use different compression methods for a different file within the same RAR package, or maybe something is not quite right within RAR5Parser._parse_file_block/RAR3Parser._parse_file_header? 

Note: use WinRAR or UnRAR.exe by itself is able to extract the file correctly without any issue.

**Comment by sirrus233** [comment]
I don't think the issue here has to do with the RAR file format. As you have pointed out, the open_unrar function is used to shell out to an executable that actually does the extraction. This library creates an invokable commandline string (to invoke unrar.exe, say) and then passes a filename as an argument. However, this filename is sanitized and all backslashes in the filepath are replaced by forward slashes. This means unrar.exe can't find the path, pipes nothing to STDOUT, and the library interprets this as 0 bytes of data.

I don't know why this bug would be new - but I have submitted a pull request that does fix this issue on my machine. It's a one-line fix, so you can give it a try pretty easily.

**Comment by arnau126** [comment]
Same issue here!
@sirrus233 fix (PR #69 ) works for me.

**Comment by mxmlnkn** [comment]
I have the same error with some files. I run the same test with Github Actions on macOS and ubuntu but I have this error only on macOS for some reason. Installing the PR via:

```bash
python3 -m pip install --user --force-reinstall git+https://github.com/sirrus233/rarfile.git@sirrus233-bugfix#egginfo=rarfile
```

does not fix the problem for me.

**Comment by iliatimofeev** [comment]
```
brew install carlocab/personal/unrar
````
will help on macos

**Comment by prezime** [comment]
thanks [iliatimofeev](https://github.com/iliatimofeev)

**Comment by leng-yue** [comment]
Seems like the `nodash=False` generates incorrect cmd for bsdtar.

**Comment by enrique-zarate** [comment]
@iliatimofeev  Do you know an alternative for linux?

**Comment by mxmlnkn** [comment]
> @iliatimofeev Do you know an alternative for linux?

I would try `sudo apt install unrar` or `sudo apt install libarchive-tools`.

**Comment by enrique-zarate** [comment]
I ended up using `unrar-free`
Full command: `sudo apt-get install unrar-free`

**Comment by enrique-zarate** [comment]
> > @iliatimofeev Do you know an alternative for linux?
> 
> I would try `sudo apt install unrar` or `sudo apt install libarchive-tools`.

I ended up using `unrar-free`
Full command: `sudo apt-get install unrar-free`
